### ISSUE TITLE
Use try-catch on final grade

### ISSUE THREAD

**Issue by didymusbenson** [byuicampuscd/gamification-space#18]

**Comment by didymusbenson** [comment]
From #7 
403 - Permissions (Not released) - need to confirm
404 - Not found (Teacher or TA)

> valence.js:11069 GET https://byui.brightspace.com/d2l/api/le/1.5/64229/grades/final/values/myGradeValue 404 (Not Found)

404 results from not having a final grade value (instructor) or not having it released to you (student).

Valence.js handles the 404 with this:

> else if (res.statusCode === 404) {
>                                data.finalCalculatedGrade = {
>                                    gradeID: "Final",
>                                    gradeName: "Final Calculated Grade",
>                                    catID: "",
>                                    maxPoints: null,
>                                    weight: null,
>                                    excludeFromFinalGradeCalculation: null,
>                                    pointsDenominator: 100,
>                                    pointsNumerator: 100,
>                                    weightedDenominator: 100,
>                                    weightedNumerator: 100,
>                                    description: "Final Calculated Grade",
>                                    gradeType: "Final Calculated Grade",
>                                    isGraded: true
>                                };
>                                asynCallback(null, data.finalCalculatedGrade);
>                            }

**Comment by didymusbenson** [comment]
Is our goal with the try-catch to just get it to a point where it will display the error at all? The error handling (above) seems to take care of the problem caused by the 404.

**Comment by meeple142** [comment]
Ya with a try catch the error wont end up on the console

**Comment by didymusbenson** [comment]
Is handled, no way to remove the 404 from the debugging screen.
