### ISSUE TITLE
Errors on getting final grade if not a student/impersonating a student

### ISSUE THREAD

**Issue by meeple142** [byuicampuscd/gamification-space#7]

**Comment by g-mips** [comment]
403 - Permissions (Not released) - need to confirm
404 - Not found (Teacher or TA)

**Comment by didymusbenson** [comment]
> valence.js:11069 GET https://byui.brightspace.com/d2l/api/le/1.5/64229/grades/final/values/myGradeValue 404 (Not Found)

404 results from not having a final grade value (instructor) or not having it released to you (student).

Valence.js handles the 404 with this:

> else if (res.statusCode === 404) {
>                                data.finalCalculatedGrade = {
>                                    gradeID: "Final",
>                                    gradeName: "Final Calculated Grade",
>                                    catID: "",
>                                    maxPoints: null,
>                                    weight: null,
>                                    excludeFromFinalGradeCalculation: null,
>                                    pointsDenominator: 100,
>                                    pointsNumerator: 100,
>                                    weightedDenominator: 100,
>                                    weightedNumerator: 100,
>                                    description: "Final Calculated Grade",
>                                    gradeType: "Final Calculated Grade",
>                                    isGraded: true
>                                };
>                                asynCallback(null, data.finalCalculatedGrade);
>                            }

**Comment by didymusbenson** [comment]
403 - nonissue, doesn't happen.

**Comment by didymusbenson** [comment]
COPYING RELEVANT INFORMATION AND MOVING IT TO ISSUE #18
