### ISSUE TITLE
Error when not a student/ impersonating one

### ISSUE THREAD

**Issue by meeple142** [byuicampuscd/gamification-space#8]
The folowing line errors when not a student
`name: constant.RANKS[rankIndex].name,`
Error:

> Uncaught TypeError: Cannot read property 'name' of undefined     controller.js :50 

File Context:
https://github.com/byuicampuscd/gamification-space/blob/master/controller.js#L47-L53

**Comment by didymusbenson** [comment]
Appears to have been resolved, error no longer occurs for non-students.
